### ISSUE TITLE
Move to JuliaMath?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/HypergeometricFunctions.jl#19]
I'm now an owner at JuliaMath so could transfer this package there if people agree. This would raise exposure, and increase the pool of possible maintainers/contributors. 

@MikaelSlevinsky @jwscook Any concerns with this?

@ViralBShah I assume it's fine for me to do this (as you made me an owner of JuliaMath) but let me know if you object.

**Comment by jwscook** [comment]
None from me.

**Comment by ViralBShah** [comment]
@dlfivefifty Yes, perfectly fine! That is why I made you owner :-)

**Comment by MikaelSlevinsky** [comment]
I'd want to have push access wherever it ends up, otherwise I'm fine with the move.

**Comment by ViralBShah** [comment]
Of course! JuliaMath could also use more owners. Can I add you as owner?

**Comment by dlfivefifty** [comment]
Done!

**Comment by MikaelSlevinsky** [comment]
Ok!
