### ISSUE TITLE
Grant @MikaelSlevinsky push and write access/ownership

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaMath/HypergeometricFunctions.jl#21]
This seems to have been lost during the transfer from JuliaApproximation. I'm still working on a paper describing the rational approximations in this repository mostly implemented by PR https://github.com/JuliaMath/HypergeometricFunctions.jl/pull/14: but I don't need lack of push access to get in the way of further development, and I wouldn't want to bother anyone with revisions to the code.

**Comment by dlfivefifty** [comment]
Invite sent

**Comment by MikaelSlevinsky** [comment]
Hey so I just got booted from JuliaMath because I didn't have 2-factor authentication.

I just added that, so it should be possible to re-add me as a collaborator. If someone from JuliaMath could do this, I would appreciate that.

**Comment by dlfivefifty** [comment]
It still says you are a collaborator...

**Comment by MikaelSlevinsky** [comment]
@andreasnoack granted me access again within a day.

But if you're available for issues, there's always this one https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl/issues/115
