### ISSUE TITLE
Include in SpecialFunctions.jl?

### ISSUE THREAD

**Issue by bayesthm** [JuliaMath/HypergeometricFunctions.jl#31]
Hey all,  this is great work.  Have you considered trying to incorporate it into [SpecialFunctions.jl](https://github.com/JuliaMath/SpecialFunctions.jl)?  Just a thought.

**Comment by dlfivefifty** [comment]
Thanks! Why would it be helpful for SpecialFunctions.jl?

If you are really keen on this probably better to open an issue on SpecialFunctions.jl to open discussion. But you'd need to be prepared to do the PR yourself, which will likely be a lot of work with addressing requests for changes.

**Comment by MikaelSlevinsky** [comment]
I think the SpecialFunctions.jl repository is for, generally speaking, functions with fewer parameters for which there are known algorithms (some dating back to the '60s) that provide relative (or absolute in oscillatory cases) error that is a modest multiple of the unit of least (working) precision.

For generalized hypergeometric functions, I think the same technical guarantee is much harder to prove in an algorithm; here, I would not even guarantee a single correct digit (relative or absolute).
