### ISSUE TITLE
Why no ₁F₁?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/HypergeometricFunctions.jl#32]
Or `M` or `U`?

What's `drummond1F1`?
```julia
# ₁F₁(α,β;z)
function drummond1F1(α::T1, β::T2, z::T3; kmax::Int = 10_000) where {T1, T2, T3}
```

**Comment by MikaelSlevinsky** [comment]
Could be added, though exporting single capital letters seems fraught. At some point, I thought it best to funnel all usage through `pFq`.

`drummond1F1` is a rational approximation algorithm to `1F1`. For `pFq` with p <= q, the Drummond algorithm is anecdotally stable.

**Comment by dlfivefifty** [comment]
No need to export: I think `HypergeometricFunctions.M` is very clean

**Comment by MikaelSlevinsky** [comment]
Probably `M` can be added immediately. For `U`, I think we can use its representation as a linear combination of `M`s and rationally approximate its asymptotic expansion, `2F0`, via `wenigerpFq`.

**Comment by MikaelSlevinsky** [comment]
`_₁F₁(a, b, z)` and `HypergeometricFunctions.M(a, b, z)` are added and special cased in `pFq`.
