### ISSUE TITLE
Failures on Julia nightly

### ISSUE THREAD

**Issue by andreasnoack** [JuliaMath/HypergeometricFunctions.jl#37]
Looks like they are all `Float16` related. See https://travis-ci.com/github/JuliaMath/HypergeometricFunctions.jl/jobs/442111947

**Comment by andreasnoack** [comment]
It looks like lights are green again

**Comment by dlfivefifty** [comment]
Btw in packages I maintain I don’t support nightly: was burnt once changing all ` + ` to ` .+ ` in a change that was reverted. So I wait to rc before worrying about failures
