### ISSUE TITLE
How to reference?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/HypergeometricFunctions.jl#42]
@MikaelSlevinsky any preference how to reference?

CC @TSGut

**Comment by MikaelSlevinsky** [comment]
Just the repository's fine for now.

**Comment by dlfivefifty** [comment]
Authors?

**Comment by DanielVandH** [comment]
> Just the repository's fine for now. 

@MikaelSlevinsky Is this still your preferred way of referencing? Just wondering in case "for now" was alluding to something else eventually being released.

**Comment by MikaelSlevinsky** [comment]
The three references are added to the readme. Thanks for filing the issue!
