### ISSUE TITLE
Make DualNumbers a weak dependency

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/HypergeometricFunctions.jl#57]
DualNumbers has been a direct dependency of this package for about as long as this package has tracked its dependencies. Methods of some internal functions are defined for `Dual` but dual numbers don't seem to actually be used. As far as I can tell, it would be a non-functional change from this package's perspective to remove the dependency and the methods. That said, I don't know whether there was a reason (e.g. integration with some other specific downstream package) that these methods are defined for `Dual`. If it's important to have those methods defined, they could potentially be moved to an extension (for Julia 1.9+), or otherwise perhaps the dependency can be removed altogether.

**Comment by dlfivefifty** [comment]
I don’t there’s a deep reason other than at one point I tried to auto-diff a hyper geometric function. I think just removing the code is fine
