### ISSUE TITLE
₂F₁ specialization of pFqweniger not being used

### ISSUE THREAD

**Issue by PythonNut** [JuliaMath/HypergeometricFunctions.jl#62]
As far as I can tell, the general implementation is being run instead:

```julia
julia> @which HypergeometricFunctions.pFqweniger((1, 2), (4,), 1.0)
pFqweniger(α::Tuple{Vararg{T1, p}}, β::Tuple{Vararg{T2, q}}, z::T3; kmax) where {p, q, T1, T2, T3} in HypergeometricFunctions at ~/.julia/packages/HypergeometricFunctions/K89ff/src/weniger.jl:14
```

Naturally, this also propagates up to `_₂F₁`.

**Comment by MikaelSlevinsky** [comment]
Ah that's because I haven't tagged since last week... I guess it's just on master at the moment? The special case is much faster, so it'll be fun tagging a new patch release soon!

**Comment by PythonNut** [comment]
Ah my mistake! Thanks for adding the special case! I'll update to master for now.
