### ISSUE TITLE
Is 1F1 broken?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaMath/HypergeometricFunctions.jl#66]
Thank you in advance for your bug report @ioannisPApapadopoulos @TSGut

**Comment by ioannisPApapadopoulos** [comment]
Sorry! So actually before I even get to the change that affected me, 1F1 seems to throw warning for certain values of x. E.g.

```
_₁F₁.(5/6,1/2,-4.9^2)
┌ Warning: Rational approximation to ₂F₀ reached the maximum type of (1048576, 1048576).
└ @ HypergeometricFunctions C:\Users\john.papad\.julia\dev\HypergeometricFunctions\src\weniger.jl:98
-0.03244131055572879
```

This comes from the recent commit df46b74b4a3db4486d8b7a40ec80c91f02352ec7

https://github.com/JuliaMath/HypergeometricFunctions.jl/commit/df46b74b4a3db4486d8b7a40ec80c91f02352ec7

**Comment by ioannisPApapadopoulos** [comment]
If I fix to the commit 089e208d5869dd09b0f12010dd28d1026a18a0ca (commit before the warning comes in) then it's actually quite tricky to nail down a specific change because quite a few come in.

e.g. 

```
x = -5:0.1:5;
git checkout 089e208d5869dd09b0f12010dd28d1026a18a0ca
new = _₁F₁.(5/6,1/2,-x.^2)
git checkout 98eab44b111549e5c20e238748f34658ac3e23f1
old = _₁F₁.(5/6,1/2,-x.^2)
norm(new-old, Inf)
>> 0.00019090947307336126
```

If I compare to older commits, then the difference is even bigger

**Comment by MikaelSlevinsky** [comment]
Wowza! I wonder what's gonna happen to the guy who pushed those changes

**Comment by dlfivefifty** [comment]
Maybe these bugs can be avoided by just writing a MeijerGFunctions.jl and have this package call that?
