### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by oschulz** [JuliaMath/HypergeometricFunctions.jl#83]
@devmotion can we do a new release? The current version still pulls in DualNumbers (removed in #59).

**Comment by devmotion** [comment]
Sure, I opened https://github.com/JuliaMath/HypergeometricFunctions.jl/pull/82 a while ago to get the approval by one of the maintainers (I only contributed #59).

**Comment by oschulz** [comment]
Thanks @devmotion !

**Comment by oschulz** [comment]
(and thanks @dlfivefifty !)
